title:            The Insignificant Cookbook
tagline:          'Cooking recipes for the discerning geek'
url:              http://windgazer.github.io/cookbook
author:           Martin 'Windgazer' Reurings
