title:            The Insignificant Pebble
tagline:          'The meandering experiences of a Geek'
url:              http://pebble.windgazer.nl
author:           Martin Reurings

markdown: redcarpet

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
